version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo_data:/data/db

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo_data:
